import "./jquery.waypoints.min.js"
import "./nav.js"
import "./slider.js"
import "./team.js"
import "./form.js"
import "./clock"

import "../css/style.css"
import "../css/nav.css"
import "../css/hero.css"
import "../css/feature.css"
import "../css/descriptions.css"
import "../css/team.css"
import "../css/sign-up.css"
import "../css/fontello.css"
import "../css/clock.css"
import "../css/footer.css"